### ISSUE TITLE
Default docs page doesn't show much helpful

### ISSUE THREAD

**Issue by FreedomBen** [fireproofsocks/xray#3]
For some reason in hex.pm when visiting https://hexdocs.pm/xray/ (or https://hexdocs.pm/xray/api-reference.html which we get redirected to), the only docs shown are the summary which I think gets pulled from the first section here: 
 https://github.com/fireproofsocks/xray/blob/v1.1.1/lib/xray.ex#L3-L4

This makes it seem like there isn't any documentation.  Going to https://hexdocs.pm/xray/Xray.html#content shows that isn't the case.  I tried looking through the ExDoc docs and elixir documentation docs but couldn't figure out why that would be happening, otherwise I'd just send a PR.  I wonder if rebuilding and re-publishing a new version would fix it.  Newer built packages that don't have a `pages` dir seem to behave correctly.  Just a thought.

This is re: this comment on stack overflow:  https://stackoverflow.com/questions/71769514/what-does-the-operator-do-in-elixir/71769515#comment126864443_71769515

![Screenshot from 2022-04-10 17-23-51](https://user-images.githubusercontent.com/4177139/162644641-2c46fb7a-2648-4cbe-a06b-e708f0e68ba8.png)

**Comment by fireproofsocks** [comment]
I understand the bewilderment, but this is normal functionality for ExDocs (you can see the "tabs" for Pages and Modules).  Alternatively, you can specify dedicated markdown pages to be the default -- that's useful if you want to include guides or how-tos, but otherwise it's just a summary.  Generally, the habit to get into with Elixir packages is to get familiar with navigating the **modules** -- that's where all the functions are documented.  Sometimes it seems like you've stepped into an empty house (and sometimes projects are undocumented), but a lot of times you have to click thru to the modules.  It can be frustrating, and I didn't really have an appreciation for the organization until I had to wander through the Erlang docs, and I could see how much Elixir has improved on that.

I've added the `README` to the docs and published v1.2.0 so the landing page is a nicer handoff.
